name: semantics_app
description: "A Flutter projec to manage semantics."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  mocktail: ^1.0.4

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
